# Generated by Django 5.2.3 on 2025-06-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('column', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='task',
            field=models.CharField(),
        ),
        migrations.AlterUniqueTogether(
            name='taskmodel',
            unique_together={('task', 'column')},
        ),
    ]
